### ISSUE TITLE
mstpr-brainbot - Extra gas in native token will be sent to the WooCrossRouterForWidget contract instead of the user

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-woofi-swap-judging#11]
mstpr-brainbot

medium

# Extra gas in native token will be sent to the WooCrossRouterForWidget contract instead of the user

## Summary
When users do a cross swap using the widget contract the excess fee will be sent to the widget contract but not to the user.
## Vulnerability Detail
First, let's understand the cross swap cycle when its initiated by an user from Widget contract:

[User calls Widget](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossRouterForWidget.sol#L104-L111)
[Widget calls WooFiCrosschainRouter](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossRouterForWidget.sol#L133)
[WooFiCrosschainRouter calls StargateRouter](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L256-L267) **4th argument is the "msg.sender" which is the refund address for LayerZero**
[StargateRouter calls StargateBridge](https://github.com/stargate-protocol/stargate/blob/c647a3a647fc693c38b16ef023c54e518b46e206/contracts/Router.sol#L133)
[StargateBridge calls L0Endpoint](https://github.com/stargate-protocol/stargate/blob/c647a3a647fc693c38b16ef023c54e518b46e206/contracts/Bridge.sol#L304)
[L0Endpoint calls UltraLightNode](https://github.com/LayerZero-Labs/LayerZero/blob/48c21c3921931798184367fc02d3a8132b041942/contracts/Endpoint.sol#L95)

and finally the fee is calculated in the UltraLightNode contract as follows:
```solidity
function send(address _ua, uint64, uint16 _dstChainId, bytes calldata _path, bytes calldata _payload, address payable _refundAddress, address _zroPaymentAddress, bytes calldata _adapterParams) external payable override onlyEndpoint {
        .
        .
        .
        // compute all the fees
        -> uint relayerFee = _handleRelayer(dstChainId, uaConfig, ua, payload.length, _adapterParams);
        -> uint oracleFee = _handleOracle(dstChainId, uaConfig, ua);
        -> uint nativeProtocolFee = _handleProtocolFee(relayerFee, oracleFee, ua, _zroPaymentAddress);

        // total native fee, does not include ZRO protocol fee
        -> uint totalNativeFee = relayerFee.add(oracleFee).add(nativeProtocolFee);

        // assert the user has attached enough native token for this address
        -> require(totalNativeFee <= msg.value, "LayerZero: not enough native for fees");
        // refund if they send too much
        -> uint amount = msg.value.sub(totalNativeFee);
        if (amount > 0) {
            -> (bool success, ) = _refundAddress.call{value: amount}("");
            -> require(success, "LayerZero: failed to refund");
        }

        // emit the data packet
        bytes memory encodedPayload = abi.encodePacked(nonce, localChainId, ua, dstChainId, dstAddress, payload);
        emit Packet(encodedPayload);
    }
```

As we can observe in above code snippet, if there are excess native sent then it's refunded back to the refund address. Now, let's trace back and see what's the refund address that's been sent to UltraLightNode. The refund address is set to "msg.sender" first in the WooFiCrosschainRouter (see above) and then the address passed on to others. Since the "msg.sender" is the Widget contract and not the user, the excess native tokens will be sent to the Widget contract.
## Impact
Although it seems like an user mistake to sent more native than calculated, the issue is I think medium because:
Users query the LayerZero fee off-chain and sign the tx onchain. The time spent between querying off chain and sending the tx can make the fee sent lesser or higher. If its lesser the tx will revert, if its higher the excess is lost for the user. Hence, it is very likely that the refund is required. Ideally users should be sending such fee amount that it is slightly more than the estimated fee. 
## Code Snippet
https://github.com/LayerZero-Labs/LayerZero/blob/48c21c3921931798184367fc02d3a8132b041942/contracts/UltraLightNodeV2.sol#L116-L161
## Tool used

Manual Review

## Recommendation
instead of msg.sender, use tx.origin inside the crosschainrouter contract

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/woonetwork/WooPoolV2/pull/112/commits/7306a2bf67a2a849feadb7e022d8508ea0f6f450

**Comment by Banditx0x** [comment]
Escalate.

lol

**Comment by WangSecurity** [comment]
Can you give reasons for escalation?

**Comment by Banditx0x** [comment]
Excess gas is generally refunded for bridging as a user cannot know the precise amount of gas required to complete a cross-chain transaction

**Comment by CarlosAlegreUr** [comment]
> 3\. inCaseTokenGotStuck



> Can you give reasons for escalation?

My issue #78 is a duplicate of this one. And I think the reasons exposed for invalidity can be discussed more to make the findings valid like so:

Lets address them 1 by 1. See reasons in [this comment](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/11#issuecomment-2037593512).

1. If it's nullified due to not being a core functionality, why then bothering including it in the audit scope?, doesnt really make sense for me excluding not "core" funtionalities, as far as I understand ALL code in scope is part of the audit and all functionalities are under review, whether they are core or peripherical, if they 1) behave in an unexpected way harming users or protocol, 2) or are implemented inorrectly , these should be a valid Medium. And this issue has these 2 properties. As of my understanding those are valid Sherlok criteria. If there is an isssue with a code under scope with the 2 properties described, it's a valid issue whether is related to "core" functionalities or not. Also the fact that the team addressed and fixed the issue makes it look more like an actual isse that should be valid.

So summing up this first point, the code has these 2 properties that would make it valid: 1) Behaves in unexpeted way that harms protocol with extra expenses as the use of `inCaseTokenGotStuck()` function for these scenario is an ***unexpected avoidable expense which manifests and undesired behaviour of the system***. And it is even more clear it was an unexpected, incorrect implementaiton (property number 2) and not intended as the team fixed it. See fix comment [here](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/11#issuecomment-2025170629)

2. I refer to what BanditoxOx said in a comment on the issue:
```
gas is generally refunded for bridging as a user cannot know the precise amount of gas required to complete a cross-chain transaction
```

3. To answer the 3rd invalidaton reason lets go back to a point addressed to argue reason 1. It is true that Woofi can do that and then send back all the gas to the actual msg.sender, but that's extra, unexpected unnecesary expenses for the protocol a.k.a. a loss. They even have fixed the issue as we can see in the comments so they did not expect to use the `inCaseTokenGotStuck()` function for this scenario. I think ***unexpected avoidable expenses which manifest and undesired behaviour of the system*** are a valid concern and this issues should be valid.

For these reasons I think the reasons provided to invalidate the finding should be reviewed and the issue should be valid.

**Comment by WangSecurity** [comment]
Firstly, thank you for such a thorough message, it's very insightful. 

Secondly, the fact that the team fixed it, it doesn't mean that the issue is valid medium/high.

Thirdly, I still believe it falls into a category of an opportunity loss. I don't think it actually harms the user since in the regular condition they shouldn't get the refund and it's a nice feature that the protocol added. Therefore, I believe it's a not a core functionality break and the cotnract still works as expected the only problem is that it receives the refund insted of the msg.sender.

Therefore, I believe it should remain as it is under Sherlock's rules (opportunity loss). I don't say it's completely wrong/invalid, I just don't see it as medium/high. Low at max, but I may be wrong here.

**Comment by Banditx0x** [comment]
In cross-chain functions, generally a pay-what-is-used model is used, where the excess gas is returned to the user. This is not unique to stargate and is true for most bridging. 

@WangSecurity your perception is that the `msg.value` passed should be an estimation of the gas required to complete the transaction, and that it is a mistake to send more. That is not actually what `msg.value` should represent. Instead `msg.value` should be the _maximum_ amount of gas a user is willing to pay. 

It is rational for a user to send $130 worth of gas for a stargate transaction estimated to only cost $100. Entering a higher `msg.value` than the estimate allows the user to specify _"I know the transaction is estimated to cost $100, but if the gas cost increases during the period after my gas estimate, then I would rather pay up to $130 in gas rather than have my transaction revert."_

If the gas refund is not correctly attributed to the `sender` of the transaction, and is rather sent to the Widget and not attributed to the sender, this disallows the sender to specify a maximum acceptable gas cost while still getting a refund for their gas.

**Comment by WangSecurity** [comment]
I totally understand what Bandit says, but this is not the main argument. I understand that it's hard to estimate the gas price correctly, but my main argument here is that it's an opportunity loss and not a core functionality. I may be wrong with that, but I still believe it should remain low. Thank you for pointing out this issue!

**Comment by Banditx0x** [comment]
You do realise that a user loses funds _every transaction_ corresponding to the extra gas forwarded unless msg.value is the EXACT amount of gas required for the transaction? And as stated before, the bridges are designed with a pay-what-is-used gas model out of necessity and not just a nice-to-have feature?

**Comment by WangSecurity** [comment]
I agree with the first question. But for the second, excuse me if "nice-to-have" sounds incorrect and I understand the model of refunding here, but I'm still of the opinion it's not core functionality and only an opportunity loss. 

I totally see and understand your finding, thank you for bringing this issue up, but I still believe it's low. If you have any other arguments that were not listed above, please share them and we'll discuss. As for me, I've already given all my reasoning. Therefore, if you don't mind we can leave it to the head of judging to decide.

**Comment by Czar102** [comment]
Was there an expectation from WOOFi to refund gas? If not, I'd rather see this as an improvement of the current system, not a security issue or a mistake – it's an odd, though valid, design decision, as far as I understand.

**Comment by CarlosAlegreUr** [comment]
> Was there an expectation from WOOFi to refund gas? If not, I'd rather see this as an improvement of the current system, not a security issue or a mistake – it's an odd, though valid, design decision, as far as I understand.

@Czar102 . There is no documentaiton specifying that. But it can be deduced by the way they coded it, as I explain in my issue #78 , section **Vulnerability Details**, which is a duplicate of this one.

Summing it up:

[This line](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/main/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L260) is the key that tells us that the refund is not expected to go to the team, but to the user.

You can see that the line is in the very same **WooCrossChainRouterV4** contract, the one users of the protocol use for cross-chain swaps. And the rebate address is `msg.sender`, which in this case is the final user.

So, by the context and not by documentation (because there was no provided details), we can say that the final refund address is meant to be the user. And in **WooCrossRouterForWidget** is not for the reasons these issues submited present.

**Comment by Banditx0x** [comment]
@Czar102 Yes, they pass in `msg.sender` as a parameter as the gas rebate parameter. You would get the gas refund if you called the function with an EOA rather than the widget. They also fixed the bug, so it isn't an intentional design decision.

**Comment by WangSecurity** [comment]
Actually, I agree that it was a mistake and incorrect address was used by the protocol. My main point was that it's not a core functionality break. 

But on the last question by Czar, I agree with the G's above.

**Comment by TradMod** [comment]
A very similar finding was accepted as medium on C4 very recently. C4 judge added: "I consider it a medium-risk issue as it is likely those transactions would have a substantial over-allocation of gas due to their cross-chain nature". I believe it will be fair enough to consider it as a medium here on sherlock as well, as there is a monetary loss for users/broken functionality. Thanks!

https://github.com/code-423n4/2024-01-decent-findings/issues/262

**Comment by WangSecurity** [comment]
Other contests are not sources of truth unfortunately, therefore, the fact that it was accepted in another contest doesn't effect this one.

**Comment by Czar102** [comment]
I'd see this as a gas optimization – it's as if the transaction consumed nearly all gas forwarded instead of only what's needed, and these issues are considered to be of Low severity.

Also, the escalation "lol" is itself making no valid arguments, so it will certainly be rejected.

**Comment by Czar102** [comment]
Result:
Low
Has duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [banditx0x](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/11/#issuecomment-2039085464): rejected

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
