### ISSUE TITLE
cats - Protocol balance can be drained due to incorrect decimal scaling on destination chain

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-03-woofi-swap-judging#30]
cats

high

# Protocol balance can be drained due to incorrect decimal scaling on destination chain

## Summary
Destination chain does not de-scale token decimals which allows an attacker to drain the contract.
## Vulnerability Detail
When a user wants to bridge `ERC-20` tokens without making any swaps neither on source, nor on destination chain the `crossSwap()` function first [transfers them in](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L92-L93), then after deducting a fee, calls to [bridge by StarGate](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L141). When [encoding the payload for the bridge](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L237), the amount to bridge is encoded from the `dstInfos.minToAmount`:

```solidity
        bytes memory payload = abi.encode(refId, to, dstInfos.toToken, dstInfos.minToAmount, dst1inch);
```

Next, when the tokens are bridged to the destination and [the payload is decoded](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L168-L171), if the received token is `ERC-20`, the [following](https://github.com/sherlock-audit/2024-03-woofi-swap/blob/65185691c91541e33f84b77d4c6290182f137092/WooPoolV2/contracts/CrossChain/WooCrossChainRouterV4.sol#L385-L495) function is called to send the funds to the final `_to` address. We can see that if the final `toToken` is the same as the `bridgedToken` (no swap requested on dst), the same amount of tokens that we sent are directly transferred to the `_to` address:

```solidity
        if (toToken == bridgedToken) {
            TransferHelper.safeTransfer(bridgedToken, to, bridgedAmount);
```

The first issue is that there is no scaling/de-scaling of token decimals when the tokens are received on the destination chain. The 2nd problem is that the protocol is deployed on `BSC` chain where [USDC](https://bscscan.com/token/0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d#readProxyContract) has 18 decimals, whilst on mainnet and most other chains it only has 6 decimals.

This allows for an attacker to bridge source token `USDC 1e18` from BSC chain to another chain where it is `USDC 1e6`, but since there is no adjustment to the decimals on the destination chain (whilst 1 BSC USDC == 1 mainnet USDC == 1$), the end receiving `_to` address will receive `1 ** (srcDecimals - dstDecimals)` excess profit which will be from any tokens available in the contract acrrued from fees or else.

This also works the same way in reverse, where users bridging `USDC` from most chains to BSC, will receive significantly less tokens due to non scaled decimals. In both cases it is a direct loss of funds for protocol and/or users.
## Impact
Direct loss of funds to protocol and/or users.
## Code Snippet
```solidity
        if (toToken == bridgedToken) {
            TransferHelper.safeTransfer(bridgedToken, to, bridgedAmount);
```
## Tool used
Manual Review
## Recommendation
Apply scaling/de-scaling of token decimals where it is needed.

**Comment by 0xcats** [comment]
Escalate
A few points I want to make: 
1. Yes, stargate is used for bridging, but I really don't see how that has anything to do with WooFi's code and their job to convert the decimals when bridging, otherwise, their contracts can be drained. The report outlines that and focuses on this protocol's code. It is their job to properly integrate with 3rd party protocols. Would they blame stargate if they got drained?

2. I did not report this under the guise of "weird ERC20 behavior", I gave an example with one of the most commonly used tokens in the whole space which is USDC and it happens to have different decimals on different chains. USDC's weird behavior is actually the blocklist - I don't think the different decimals falls under weird. Also, any and all other tokens that are supported by the protocol and have different decimals on different supported chains can be used to do the same exploit.

> 1 comment(s) were left on this issue during the judging contest.
> 
> **WangAudit** commented:
> 
> > I know contest's README says any erc20 token will be used and BSC chain is also mentioned to be used; but USDC is not explicitly mentioned to be used on BSC and I believe it is stargate which is used for bridging deals with it and the report says nothing about the bridge and was is done there (stargate deals with sending tokens from one chain to another)

**Comment by sherlock-admin2** [comment]
> Escalate
> A few points I want to make: 
> 1. Yes, stargate is used for bridging, but I really don't see how that has anything to do with WooFi's code and their job to convert the decimals when bridging, otherwise, their contracts can be drained. The report outlines that and focuses on this protocol's code. It is their job to properly integrate with 3rd party protocols. Would they blame stargate if they got drained?
> 
> 2. I did not report this under the guise of "weird ERC20 behavior", I gave an example with one of the most commonly used tokens in the whole space which is USDC and it happens to have different decimals on different chains. USDC's weird behavior is actually the blocklist - I don't think the different decimals falls under weird. Also, any and all other tokens that are supported by the protocol and have different decimals on different supported chains can be used to do the same exploit.
> 
> > 1 comment(s) were left on this issue during the judging contest.
> > 
> > **WangAudit** commented:
> > 
> > > I know contest's README says any erc20 token will be used and BSC chain is also mentioned to be used; but USDC is not explicitly mentioned to be used on BSC and I believe it is stargate which is used for bridging deals with it and the report says nothing about the bridge and was is done there (stargate deals with sending tokens from one chain to another)
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by windhustler** [comment]
The issue you are describing doesn't exist with Stargate. First of all, USDC is not available as an asset you can bridge from BNB. 
<img width="666" alt="Screenshot 2024-04-08 at 08 11 49" src="https://github.com/sherlock-audit/2024-03-woofi-swap-judging/assets/38017754/2903e255-519c-423a-8d54-1da8bbd7020d">

See the comprehensive list here: https://stargateprotocol.gitbook.io/stargate/developers/contract-addresses/mainnet. And here you can see what is available to be swapped into what: https://stargateprotocol.gitbook.io/stargate/developers/stargate-chain-paths

But we can take another example. Bridging USDC from Eth Mainnet(6 decimals) to BNB USDT(18 decimals).
StargatePools has the concept of conversion rate, and it is the way this is handled. See another issue: https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/132. 

USDC Stargate pool on Eth Mainnet has the conversion rate equal to 1, while BNB USDT Stargate Pool has the conversion rate equal to `1e12`. You can check it through the explorer:
USDC Pool Mainnet: https://etherscan.io/address/0xdf0770dF86a8034b3EFEf0A1Bb3c889B8332FF56#readContract 
USDT Pool BNB: https://bscscan.com/address/0x9aA83081AA06AF7208Dcc7A4cB72C94d057D2cda#readContract

An example:

You transfer 1e6 USDC from Ethereum, and since the conversion rate is 1 the amount is unchanged. When it lands on BNB the amount is multiplied by the conversion rate, i.e.` 1e12 * 1e6 = 1e18`.

**Comment by WangSecurity** [comment]
I admit that my reasons in the comment above are a bit off, but as I understand Windhustler above perfectly described why this report is wrong (but it's a good catch honestly). Thanks to both of them above, I don't think I can add anything here.

**Comment by Czar102** [comment]
In that case, seeing that the author agrees with it, I'm planning to reject the escalation and leave the issue as is.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xcats](https://github.com/sherlock-audit/2024-03-woofi-swap-judging/issues/30/#issuecomment-2041860877): rejected
